# Generated by Django 5.1.4 on 2024-12-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Direcror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='person/')),
                ('release_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cast')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.direcror')),
                ('droduction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.production')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tags')),
            ],
        ),
    ]
