# Generated by Django 5.1.4 on 2024-12-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cast_direcror_production_tags_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='droduction',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Direcror',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
